apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-rails-demo-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 531912627667.dkr.ecr.us-east-1.amazonaws.com/aws-demo:latest-background
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: web-config